-- Migration 001: Schema inicial
-- Tabelas principais do sistema

-- Tabela para Dívidas de Cartão de Crédito
CREATE TABLE IF NOT EXISTS public.credit_card_debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    local TEXT NOT NULL,
    debt_date TEXT,
    original_value NUMERIC,
    current_value NUMERIC,
    growth_percentage NUMERIC,
    interest_value NUMERIC,
    last_update_date TEXT,
    next_month_estimate NUMERIC,
    observation TEXT,
    negotiated BOOLEAN DEFAULT false,
    discount_percentage NUMERIC,
    paid_value NUMERIC,
    receipt_url TEXT,
    is_frozen BOOLEAN DEFAULT false,
    user_id UUID REFERENCES auth.users(id)
);

-- Tabela para Empréstimos
CREATE TABLE IF NOT EXISTS public.loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    contract_number TEXT,
    loan_date TEXT,
    creditor TEXT,
    loan_value NUMERIC,
    interest_value NUMERIC,
    final_value NUMERIC,
    total_installments INTEGER,
    paid_installments INTEGER,
    remaining_installments INTEGER,
    remaining_value NUMERIC,
    last_payment_date TEXT,
    status TEXT,
    observations TEXT,
    installments JSONB,
    balance_evolution JSONB,
    user_id UUID REFERENCES auth.users(id)
);

-- RLS
ALTER TABLE public.credit_card_debts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;

-- Políticas para credit_card_debts
CREATE POLICY "Users can view their own debts"
ON public.credit_card_debts FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own debts"
ON public.credit_card_debts FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own debts"
ON public.credit_card_debts FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own debts"
ON public.credit_card_debts FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- Políticas para loans
CREATE POLICY "Users can view their own loans"
ON public.loans FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own loans"
ON public.loans FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own loans"
ON public.loans FOR UPDATE
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own loans"
ON public.loans FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

COMMENT ON COLUMN public.credit_card_debts.is_frozen IS 'Indica se a dívida parou de crescer (juros congelados)';
