-- Migration 002: Criar tabela de ofertas de negociação

CREATE TABLE IF NOT EXISTS public.negotiation_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    debt_id BIGINT NOT NULL REFERENCES public.credit_card_debts(id) ON DELETE CASCADE,
    offer_date TEXT NOT NULL,
    original_value NUMERIC NOT NULL,
    discount_percentage NUMERIC NOT NULL,
    offer_value NUMERIC NOT NULL,
    accepted BOOLEAN DEFAULT false NOT NULL,
    notes TEXT
);

ALTER TABLE public.negotiation_offers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for all users"
ON public.negotiation_offers FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);
