-- Migration 003: Criar tabela de anexos de empréstimos

CREATE TABLE IF NOT EXISTS public.loan_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    loan_id BIGINT NOT NULL REFERENCES public.loans(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size BIGINT,
    description TEXT,
    user_id UUID
);

ALTER TABLE public.loan_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for all users"
ON public.loan_attachments FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_loan_attachments_loan_id ON public.loan_attachments(loan_id);
