-- Migration 004: Criar tabela de rendimentos

CREATE TABLE IF NOT EXISTS public.income (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    income_date TEXT NOT NULL,
    recurrence TEXT DEFAULT 'unique',
    category TEXT,
    is_active BOOLEAN DEFAULT true,
    observations TEXT
);

ALTER TABLE public.income ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own income"
ON public.income FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
