-- Migration 005: Criar tabela de metas de quitação

CREATE TABLE IF NOT EXISTS public.savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    goal_name TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id BIGINT NOT NULL,
    target_amount NUMERIC NOT NULL,
    monthly_contribution NUMERIC NOT NULL,
    saved_amount NUMERIC DEFAULT 0,
    estimated_months INTEGER,
    target_date TEXT,
    status TEXT DEFAULT 'active',
    notes TEXT,
    ai_suggestion JSONB
);

ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for all users"
ON public.savings_goals FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_savings_goals_status ON public.savings_goals(status);
CREATE INDEX IF NOT EXISTS idx_savings_goals_target ON public.savings_goals(target_type, target_id);
