-- Migration 006: Criar tabela de conversas com IA

CREATE TABLE IF NOT EXISTS public.ai_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT,
    context_type TEXT,
    context_id BIGINT,
    context_key TEXT,
    messages JSONB DEFAULT '[]'::jsonb,
    is_archived BOOLEAN DEFAULT false
);

ALTER TABLE public.ai_conversations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for all users"
ON public.ai_conversations FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_updated_at ON public.ai_conversations(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_context ON public.ai_conversations(context_type, context_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversations_context_key ON public.ai_conversations(context_key);
