-- Migration 009: Criar tabela de anexos de dívidas

CREATE TABLE IF NOT EXISTS public.debt_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    debt_id BIGINT NOT NULL REFERENCES public.credit_card_debts(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT,
    file_size BIGINT,
    description TEXT,
    user_id UUID
);

ALTER TABLE public.debt_attachments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public access for all users"
ON public.debt_attachments FOR ALL
TO anon, authenticated
USING (true)
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_debt_attachments_debt_id ON public.debt_attachments(debt_id);
